cd .\bin\release\
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Adygeya2009\ Adygeya2009
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\BenskiePorogi2019\ BenskiePorogi2019
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Cappadocia2018\ Cappadocia2018
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Celebrity\ Celerbrity
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\ConfirmitSouz2015\ ConfirmitSouz2015
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\DivnoGorie2020\ Divnogorie2020
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\DolomiteAlps2016\ DolomiteAlps2016
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Ehypet2012\ Ehypet2012
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\EhypetGroup\ EhypetGroup
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Epifan2019\ Epifan2019
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Iceland2011\ Iceland2011
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\India2013\ India2013
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Interfax2012\ Interfax2012 
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\InterfaxCorp2013\ InterfaxCorp2013
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\InterfaxOff1905\ InterfaxOff1905
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Ishutino\ Ishutino
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Kirgiz2012\ Kirgiz2012
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Konduki2019\ Konduki2019
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Konduki2019-2\ Konduki2019-2
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Laplandia2020\ Laplandia2020
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Madeira2018\ Madeira2018
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Montblanc2017\ Montblanc2017
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Moravia2016\ Moravia2016
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Morocco2013\ Morocco2013
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Morocco2013Group\ Morocco2013Group
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Myanmar2015\ Myanmar2015
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Norway2010\ Norway2010
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Norway2016\ Norway2016
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\PlescheevoLake2019\ PlescheevoLake2019
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\PraRafting\ PraRafting
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Pronsk\ Pronsk
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Scotland2017\ Scotland2017
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Seliger2019\ Seliger2019
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Solovki2019\ Solovki2019
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\SpainFrance2011\ SpainFrance2011
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\TrollTunga2016\ TrollTunga2016
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Usa2017\ Usa2017
PhotoReportGenerator.exe I:\PhotosProj\AlbumFront\Pub\Usa2Tmp\ Usa2Tmp
