//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbumFront.Components
{


    public partial class SeoInformers
    {
        protected global::System.Web.UI.WebControls.Panel RootElement;
        protected global::System.Web.UI.WebControls.PlaceHolder OneGb;
        protected global::System.Web.UI.WebControls.PlaceHolder Extreme;
        protected global::System.Web.UI.WebControls.PlaceHolder MailRu;
        protected global::System.Web.UI.WebControls.PlaceHolder Yandex;
    }
}
